### ISSUE TITLE
[SSLH] --ssl is deprecated

### ISSUE THREAD

**Issue by Thilas** [oorabona/docker-containers#1]
Hello,

I'm using SSLH docker image and I noticed an issue today while upgrading my container: `--ssl` is no longer supported and has been replaced by `--tls` (see https://github.com/yrutschle/sslh/commit/2ee0088c5fedc09ed4326694b7100cd1b24220a0 for instance).

Could you please adjust [docker-entrypoint.sh](https://github.com/oorabona/docker-containers/blob/master/sslh/docker-entrypoint.sh)?

Thanks!

**Comment by oorabona** [comment]
Hello,

Thanks for the report and sorry for the late answer.
This is fixed, please confirm on your side.

Many thanks!
